export default {
  FETCH_POKEMON_DATA_START: 'FETCH_POKEMON_DATA_START',
  FETCH_POKEMON_DATA_SUCCESS: 'FETCH_POKEMON_DATA_SUCCESS',
  FETCH_POKEMON_DATA_ERROR: 'FETCH_POKEMON_DATA_ERROR',
  UPDATE_POKEMON_NAME: 'UPDATE_POKEMON_NAME'
}